"""Shared pytest fixtures for splikit-py tests.

Reference fixtures (R-exported) live under tests/data/ and are loaded by
tests/load_r_ref.py. The fixture file is regenerated by tests/r_export/export_reference.R
when the upstream R splikit version bumps.
"""

from __future__ import annotations

from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = Path(__file__).resolve().parent / "data"


@pytest.fixture(scope="session")
def repo_root() -> Path:
    return REPO_ROOT


@pytest.fixture(scope="session")
def data_dir() -> Path:
    return DATA_DIR


@pytest.fixture(scope="session")
def r_reference_path(data_dir: Path) -> Path:
    """Path to the golden R-exported reference HDF5 fixture."""
    return data_dir / "r_reference.h5"
