"""Loader for tests/data/r_reference_hvg.h5 — the R splikit HVG (vst) golden fixture.

Generated by tests/r_export/export_hvg_reference.R. Mirrors the loader
pattern used for the M1/M2/HVE/pseudo_correlation fixture on the
`validation` branch (tests/load_r_ref.py), scoped to just this fixture.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import h5py
import numpy as np
import scipy.sparse as sp


@dataclass(frozen=True)
class RHvgReference:
    """A frozen snapshot of R splikit's find_variable_genes(method='vst') output."""

    gene_expression: sp.csc_matrix  # genes x cells, float64
    gene_names: np.ndarray  # length n_genes, rownames(gene_expression)
    events: np.ndarray  # find_variable_genes()$events, same order as gene_names
    standardize_variance: np.ndarray  # float64, same order

    splikit_version: str
    r_version: str
    generated_at: str
    blas_vendor: str
    loess_span: float


def _decode_strings(arr: np.ndarray) -> np.ndarray:
    if arr.dtype.kind == "S" or arr.dtype == object:
        return np.array(
            [x.decode("utf-8") if isinstance(x, bytes) else str(x) for x in arr]
        )
    return arr.astype(str)


def _read_attr(f: h5py.File, name: str) -> str:
    if name not in f.attrs:
        return ""
    val = f.attrs[name]
    if isinstance(val, bytes):
        return val.decode("utf-8")
    if isinstance(val, np.ndarray) and val.size == 1:
        v = val.item()
        return v.decode("utf-8") if isinstance(v, bytes) else str(v)
    return str(val)


def _read_attr_float(f: h5py.File, name: str, default: float = 0.3) -> float:
    if name not in f.attrs:
        return default
    val = f.attrs[name]
    if isinstance(val, np.ndarray) and val.size == 1:
        return float(val.item())
    return float(val)


def load_hvg_reference(path: str | Path) -> RHvgReference:
    """Load ``tests/data/r_reference_hvg.h5`` (or any compatible file)."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"R HVG reference fixture not found: {path}\n"
            "Regenerate via: Rscript tests/r_export/export_hvg_reference.R"
        )

    with h5py.File(path, "r") as f:
        ge = f["gene_expression"]
        indptr = np.asarray(ge["indptr"][:], dtype=np.int64)
        indices = np.asarray(ge["indices"][:], dtype=np.int64)
        data = np.asarray(ge["data"][:], dtype=np.float64)
        shape = tuple(int(x) for x in ge["shape"][:])
        gene_expression = sp.csc_matrix((data, indices, indptr), shape=shape)
        gene_names = _decode_strings(ge["gene_names"][:])

        hvg = f["find_variable_genes"]
        events = _decode_strings(hvg["events"][:])
        standardize_variance = np.asarray(
            hvg["standardize_variance"][:], dtype=np.float64
        )

        return RHvgReference(
            gene_expression=gene_expression,
            gene_names=gene_names,
            events=events,
            standardize_variance=standardize_variance,
            splikit_version=_read_attr(f, "splikit_version"),
            r_version=_read_attr(f, "r_version"),
            generated_at=_read_attr(f, "generated_at"),
            blas_vendor=_read_attr(f, "blas_vendor"),
            loess_span=_read_attr_float(f, "loess_span"),
        )
