"""Loaders for the R-exported HDF5 reference fixtures.

Two flavours:

* :func:`load_reference` — synthetic toy fixture from
  ``tests/r_export/export_reference.R``. Small, can be committed.
* :func:`load_merfish_reference` — real-data slice from the trained MultiGEDI
  model on c170 (``tests/r_export/export_merfish_reference.R``). 80+ MB,
  never committed; tests skip when missing.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import h5py
import numpy as np
import scipy.sparse as sp


@dataclass(frozen=True)
class RReference:
    """A frozen snapshot of R splikit's reference outputs on the toy dataset."""

    m1: sp.csc_matrix
    m2: sp.csc_matrix
    group_id: np.ndarray
    row_names_mtx: np.ndarray
    group_kind: np.ndarray
    group_count: np.ndarray
    chr_arr: np.ndarray | None
    start: np.ndarray | None
    end: np.ndarray | None
    strand: np.ndarray | None

    # Optional reference outputs (None on older fixtures that don't carry them).
    hve_events: np.ndarray | None
    hve_sum_deviance: np.ndarray | None
    pcor_events: np.ndarray | None
    pcor_coxsnell: np.ndarray | None
    pcor_nagelkerke: np.ndarray | None
    pcor_zdb: np.ndarray | None  # events × cells, dense float64

    # Optional obs (barcode + sample_id via R's `^.{16}-(.*$)` regex).
    obs_names: np.ndarray | None
    sample_ids: np.ndarray | None

    splikit_version: str
    r_version: str
    generated_at: str
    blas_vendor: str
    min_row_sum: int
    zdb_seed: int


@dataclass(frozen=True)
class RMerfishReference:
    """A frozen snapshot of R splikit's reference outputs on the real
    MultiGEDI-MERFISH single-sample slice."""

    m1: sp.csc_matrix                      # events × cells, float64
    m2: sp.csc_matrix                      # events × cells, float64 (recomputed on subset)
    zdb: np.ndarray                        # events × cells, float64 dense
    zdb_rownames: np.ndarray               # length n_events
    zdb_colnames: np.ndarray               # length n_cells

    row_names_mtx: np.ndarray              # length n_events; aligns with m1.rows
    group_id_dense: np.ndarray             # int32, dense 0..G-1
    group_kind: np.ndarray                 # 'S' or 'E', length n_events
    group_count: np.ndarray                # int32, length n_events
    chr_arr: np.ndarray
    start: np.ndarray
    end: np.ndarray
    strand: np.ndarray

    hve_events: np.ndarray                 # event ids that survived min_row_sum
    hve_sum_deviance: np.ndarray           # float64, len == len(hve_events)

    pcor_events: np.ndarray                # all events (length n_events)
    pcor_coxsnell: np.ndarray              # float64, NaN for early-return events
    pcor_nagelkerke: np.ndarray            # float64

    sample_id: str
    splikit_version: str
    r_version: str
    generated_at: str
    blas_vendor: str
    min_row_sum: int


def _decode_strings(arr: np.ndarray) -> np.ndarray:
    """Convert HDF5 byte strings to Python str."""
    if arr.dtype.kind == "S" or arr.dtype == object:
        return np.array([x.decode("utf-8") if isinstance(x, bytes) else str(x)
                         for x in arr])
    return arr.astype(str)


def _read_csc(group: h5py.Group) -> sp.csc_matrix:
    indptr = np.asarray(group["indptr"][:], dtype=np.int64)
    indices = np.asarray(group["indices"][:], dtype=np.int64)
    data = np.asarray(group["data"][:], dtype=np.float64)
    shape = tuple(int(x) for x in group["shape"][:])
    return sp.csc_matrix((data, indices, indptr), shape=shape)


def _read_attr(f: h5py.File, name: str) -> str:
    if name not in f.attrs:
        return ""
    val = f.attrs[name]
    if isinstance(val, bytes):
        return val.decode("utf-8")
    if isinstance(val, np.ndarray) and val.size == 1:
        v = val.item()
        return v.decode("utf-8") if isinstance(v, bytes) else str(v)
    return str(val)


def _maybe_array(group: h5py.Group, name: str) -> np.ndarray | None:
    if name not in group:
        return None
    arr = group[name][:]
    if arr.dtype.kind == "S" or arr.dtype == object:
        return _decode_strings(arr)
    return np.asarray(arr)


def _read_attr_int(f: h5py.File, name: str, default: int = 0) -> int:
    if name not in f.attrs:
        return default
    val = f.attrs[name]
    if isinstance(val, np.ndarray) and val.size == 1:
        return int(val.item())
    return int(val)


def load_merfish_reference(path: str | Path) -> RMerfishReference:
    """Load the real-data MERFISH MultiGEDI slice fixture.

    Generated by ``tests/r_export/export_merfish_reference.R`` on c170.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"MERFISH R reference fixture not found: {path}\n"
            "Regenerate via: ssh c170 'cd <repo> && module load r/4.4.0 && "
            "Rscript tests/r_export/export_merfish_reference.R "
            "--out tests/data/r_reference_merfish.h5'"
        )

    with h5py.File(path, "r") as f:
        m1 = _read_csc(f["m1"])
        m2 = _read_csc(f["m2"])

        zdb_flat = np.asarray(f["zdb"][:], dtype=np.float64)
        zdb_shape = tuple(int(x) for x in f["zdb_shape"][:])
        # rhdf5 writes dense matrices flattened in column-major (R) order;
        # reshape with order='F' so we recover the original layout, then
        # cast to a contiguous array for downstream consumers.
        zdb = np.ascontiguousarray(zdb_flat.reshape(zdb_shape, order="F"))
        zdb_rownames = _decode_strings(f["zdb_rownames"][:])
        zdb_colnames = _decode_strings(f["zdb_colnames"][:])

        ed = f["eventdata"]
        row_names_mtx = _decode_strings(ed["row_names_mtx"][:])
        group_id_dense = np.asarray(ed["group_id_dense"][:], dtype=np.int32)
        group_kind = _decode_strings(ed["group_kind"][:])
        group_count = np.asarray(ed["group_count"][:], dtype=np.int32)
        chr_arr = _decode_strings(ed["chr"][:])
        start = np.asarray(ed["start"][:], dtype=np.int64)
        end = np.asarray(ed["end"][:], dtype=np.int64)
        strand = _decode_strings(ed["strand"][:])

        hve = f["find_variable_events"]
        hve_events = _decode_strings(hve["events"][:])
        hve_sum_deviance = np.asarray(hve["sum_deviance"][:], dtype=np.float64)

        pc = f["pseudo_correlation"]
        pcor_events = _decode_strings(pc["events"][:])
        pcor_coxsnell = np.asarray(pc["coxsnell"][:], dtype=np.float64)
        pcor_nagelkerke = np.asarray(pc["nagelkerke"][:], dtype=np.float64)

        return RMerfishReference(
            m1=m1, m2=m2,
            zdb=zdb, zdb_rownames=zdb_rownames, zdb_colnames=zdb_colnames,
            row_names_mtx=row_names_mtx,
            group_id_dense=group_id_dense,
            group_kind=group_kind,
            group_count=group_count,
            chr_arr=chr_arr,
            start=start, end=end,
            strand=strand,
            hve_events=hve_events, hve_sum_deviance=hve_sum_deviance,
            pcor_events=pcor_events,
            pcor_coxsnell=pcor_coxsnell,
            pcor_nagelkerke=pcor_nagelkerke,
            sample_id=_read_attr(f, "sample_id"),
            splikit_version=_read_attr(f, "splikit_version"),
            r_version=_read_attr(f, "r_version"),
            generated_at=_read_attr(f, "generated_at"),
            blas_vendor=_read_attr(f, "blas_vendor"),
            min_row_sum=_read_attr_int(f, "min_row_sum", 1),
        )


def load_reference(path: str | Path) -> RReference:
    """Load ``tests/data/r_reference.h5`` (or any compatible file)."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"R reference fixture not found: {path}\n"
            "Regenerate via: Rscript tests/r_export/export_reference.R"
        )

    with h5py.File(path, "r") as f:
        m1 = _read_csc(f["m1"])
        m2 = _read_csc(f["m2"])
        ed = f["eventdata"]
        group_id = np.asarray(ed["group_id"][:], dtype=np.int32)
        row_names_mtx = _decode_strings(ed["row_names_mtx"][:])
        group_kind = _decode_strings(ed["group_kind"][:])
        group_count = np.asarray(ed["group_count"][:], dtype=np.int32)
        chr_arr = _maybe_array(ed, "chr")
        start = _maybe_array(ed, "start")
        end = _maybe_array(ed, "end")
        strand = _maybe_array(ed, "strand")

        # Optional kernel-reference outputs (HVE + pseudo_correlation + Z draw).
        hve_events: np.ndarray | None = None
        hve_sum_deviance: np.ndarray | None = None
        pcor_events: np.ndarray | None = None
        pcor_coxsnell: np.ndarray | None = None
        pcor_nagelkerke: np.ndarray | None = None
        pcor_zdb: np.ndarray | None = None
        if "find_variable_events" in f:
            hve_grp = f["find_variable_events"]
            hve_events = _decode_strings(hve_grp["events"][:])
            hve_sum_deviance = np.asarray(
                hve_grp["sum_deviance"][:], dtype=np.float64
            )
        obs_names: np.ndarray | None = None
        sample_ids: np.ndarray | None = None
        if "obs" in f:
            obs_grp = f["obs"]
            if "obs_names" in obs_grp:
                obs_names = _decode_strings(obs_grp["obs_names"][:])
            if "sample_id" in obs_grp:
                sample_ids = _decode_strings(obs_grp["sample_id"][:])
        if "pseudo_correlation" in f:
            pc = f["pseudo_correlation"]
            pcor_events = _decode_strings(pc["events"][:])
            pcor_coxsnell = np.asarray(pc["coxsnell"][:], dtype=np.float64)
            pcor_nagelkerke = np.asarray(pc["nagelkerke"][:], dtype=np.float64)
            zdb_flat = np.asarray(pc["zdb"][:], dtype=np.float64)
            zdb_shape = tuple(int(x) for x in pc["zdb_shape"][:])
            # rhdf5 flattens dense matrices column-major; reshape order='F'.
            pcor_zdb = np.ascontiguousarray(zdb_flat.reshape(zdb_shape, order="F"))

        return RReference(
            m1=m1,
            m2=m2,
            group_id=group_id,
            row_names_mtx=row_names_mtx,
            group_kind=group_kind,
            group_count=group_count,
            chr_arr=chr_arr,
            start=start,
            end=end,
            strand=strand,
            hve_events=hve_events,
            hve_sum_deviance=hve_sum_deviance,
            pcor_events=pcor_events,
            pcor_coxsnell=pcor_coxsnell,
            pcor_nagelkerke=pcor_nagelkerke,
            pcor_zdb=pcor_zdb,
            obs_names=obs_names,
            sample_ids=sample_ids,
            splikit_version=_read_attr(f, "splikit_version"),
            r_version=_read_attr(f, "r_version"),
            generated_at=_read_attr(f, "generated_at"),
            blas_vendor=_read_attr(f, "blas_vendor"),
            min_row_sum=_read_attr_int(f, "min_row_sum", 50),
            zdb_seed=_read_attr_int(f, "zdb_seed", 42),
        )
